# Generated by Django 4.1.2 on 2022-10-25 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviereview',
            old_name='review',
            new_name='movie_review',
        ),
        migrations.RenameField(
            model_name='tvreview',
            old_name='review',
            new_name='tv_review',
        ),
    ]
