# Generated by Django 4.1.2 on 2022-10-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_review_moviereview_movie_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='moviereview',
            name='reactions',
            field=models.ManyToManyField(to='main_app.reaction'),
        ),
        migrations.AddField(
            model_name='tvreview',
            name='reactions',
            field=models.ManyToManyField(to='main_app.reaction'),
        ),
    ]
