# Generated by Django 4.1.2 on 2022-10-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_movie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='reactions',
            field=models.ManyToManyField(to='main_app.reaction'),
        ),
    ]
